import { LightningElement, api } from 'lwc';
import storeFlowOutputs from '@salesforce/apex/FlowOutputHandler.storeFlowOutputsFromLWC';

export default class FlowRenderer extends LightningElement {
    
    @api
    get value() {
        return this._value;
    }
    
    set value(value) {
        this._value = value;
        this.initializeFlow();
    }
    
    @api 
    get readOnly() {
        return this._readOnly;
    }
    
    set readOnly(value) {
        this._readOnly = value;
    }
    
    _value;
    _readOnly = false;
    flowApiName;
    flowTitle = 'Flow';
    flowInputVariables = [];
    flowStatus = '';
    flowError = '';
    isLoading = false;
    sessionId = '';
    @api flowOutputsJson = '';
    flowCompleted = false;

    connectedCallback() {
        this.initializeFlow();
    }
    
    initializeFlow() {
        if (this.value) {
            this.flowApiName = this.value.flowApiName;
            this.flowTitle = this.value.flowLabel || 'Flow';
            
            // Use session ID from FlowDetails if provided, otherwise generate one
            this.sessionId = this.value.sessionId || this.generateSessionId();
            
            console.log('FlowRenderer initialized for INPUT:');
            console.log('- Flow API Name:', this.flowApiName);
            console.log('- Session ID:', this.sessionId);
            console.log('- Read Only:', this.readOnly);
            console.log('- Session ID Source:', this.value.sessionId ? 'Provided by Agent' : 'Generated by LWC');
            
            // Parse input variables if provided
            if (this.value.inputVariables) {
                try {
                    const inputVars = JSON.parse(this.value.inputVariables);
                    this.flowInputVariables = Object.keys(inputVars).map(key => ({
                        name: key,
                        type: this.getVariableType(inputVars[key]),
                        value: inputVars[key]
                    }));
                } catch (error) {
                    console.error('Error parsing input variables:', error);
                    this.flowInputVariables = [];
                }
            }
        }
    }

    // Determine the type of variable based on its value
    getVariableType(value) {
        if (typeof value === 'string') {
            return 'String';
        } else if (typeof value === 'number') {
            return Number.isInteger(value) ? 'Number' : 'Number';
        } else if (typeof value === 'boolean') {
            return 'Boolean';
        } else if (value instanceof Date) {
            return 'Date';
        } else if (Array.isArray(value)) {
            return 'SObject';
        } else if (typeof value === 'object') {
            return 'SObject';
        }
        return 'String'; // Default to String
    }

    // Handle flow status changes
    handleStatusChange(event) {
        const status = event.detail.status;
        this.flowStatus = status;
        
        console.log('Flow status changed:', status);
        console.log('Full event detail:', JSON.stringify(event.detail, null, 2));
        
        // According to lightning-flow documentation, these are the main status values
        switch (status) {
            case 'FINISHED':
                console.log('Flow completed successfully');
                this.captureAndStoreOutputs(event.detail);
                this.dispatchFlowCompleteEvent(status);
                break;
                
            case 'FINISHED_SCREEN':
                console.log('Flow finished on a screen');
                // FINISHED_SCREEN also provides outputVariables
                this.captureAndStoreOutputs(event.detail);
                this.dispatchFlowCompleteEvent(status);
                break;
                
            case 'ERROR':
                console.error('Flow encountered an error:', event.detail);
                this.handleFlowError(event.detail);
                break;
                
            case 'PAUSED':
                console.log('Flow was paused');
                // Flow is paused, no outputs available yet
                break;
                
            case 'STARTED':
                console.log('Flow has started');
                break;
                
            default:
                console.log('Unknown flow status:', status);
        }
    }
    
    // Helper method to dispatch flow complete event and notify agent
    dispatchFlowCompleteEvent(status) {
        this.flowCompleted = true;
        
        // For input components, dispatch valuechange event to notify the agent
        this.dispatchValueChangeEvent();
        
        // Also dispatch the custom flowcomplete event
        this.dispatchEvent(new CustomEvent('flowcomplete', { 
            detail: {
                status: status,
                flowApiName: this.flowApiName,
                sessionId: this.sessionId,
                hasOutputs: this.flowOutputsJson !== '',
                outputCount: this.flowOutputsJson !== '{}' ? Object.keys(JSON.parse(this.flowOutputsJson || '{}')).length : 0
            }
        }));
    }
    
    // Dispatch valuechange event for agent input components
    dispatchValueChangeEvent() {
        const outputData = this.parseFlowOutputs();
        
        console.log('Dispatching valuechange event with flow outputs:', outputData);
        
        this.dispatchEvent(new CustomEvent('valuechange', {
            detail: {
                value: {
                    flowCompleted: true,
                    flowStatus: this.flowStatus,
                    sessionId: this.sessionId,
                    flowApiName: this.flowApiName,
                    outputs: outputData,
                    outputsJson: this.flowOutputsJson,
                    completedAt: new Date().toISOString()
                }
            }
        }));
    }
    
    // Parse flow outputs for agent consumption
    parseFlowOutputs() {
        try {
            if (this.flowOutputsJson && this.flowOutputsJson !== '{}') {
                const outputData = JSON.parse(this.flowOutputsJson);
                
                // If it's the enhanced format, return just the outputs
                if (outputData.outputs) {
                    return outputData.outputs;
                }
                
                // Otherwise return the raw data
                return outputData;
            }
            return {};
        } catch (error) {
            console.error('Error parsing flow outputs:', error);
            return {};
        }
    }
    
    // Helper method to handle flow errors
    handleFlowError(eventDetail) {
        this.flowStatus = 'ERROR';
        
        // Extract error information from event detail
        const errorInfo = {
            status: 'ERROR',
            message: eventDetail.message || 'An error occurred while running the flow',
            flowApiName: this.flowApiName,
            sessionId: this.sessionId
        };
        
        this.flowError = errorInfo.message;
        console.error('Flow error details:', errorInfo);
        
        // Still try to capture any partial outputs if available
        if (eventDetail.outputVariables && eventDetail.outputVariables.length > 0) {
            console.log('Capturing partial outputs despite error');
            this.captureAndStoreOutputs(eventDetail);
        }
    }

    // Generate unique session ID for this flow execution
    generateSessionId() {
        const timestamp = Date.now();
        const random = Math.random().toString(36).substring(2, 8);
        return `${this.flowApiName}_${timestamp}_${random}`;
    }

    // Capture flow outputs and store them automatically via Apex
    async captureAndStoreOutputs(eventDetail) {
        try {
            console.log('=== CAPTURING FLOW OUTPUTS ===');
            console.log('Event Detail Keys:', Object.keys(eventDetail));
            console.log('Output Variables:', eventDetail.outputVariables);
            
            if (eventDetail.outputVariables && eventDetail.outputVariables.length > 0) {
                // Convert output variables array to object with enhanced metadata
                const outputObj = {};
                const outputMetadata = {};
                
                eventDetail.outputVariables.forEach(outputVar => {
                    console.log(`Processing output variable:`, {
                        name: outputVar.name,
                        value: outputVar.value,
                        dataType: outputVar.dataType,
                        objectType: outputVar.objectType
                    });
                    
                    // Store the actual value
                    outputObj[outputVar.name] = outputVar.value;
                    
                    // Store metadata about the variable
                    outputMetadata[outputVar.name] = {
                        dataType: outputVar.dataType || 'Unknown',
                        objectType: outputVar.objectType || null,
                        isNull: outputVar.value === null || outputVar.value === undefined
                    };
                });
                
                // Create enhanced output object with metadata
                const enhancedOutput = {
                    outputs: outputObj,
                    metadata: outputMetadata,
                    flowInfo: {
                        flowApiName: this.flowApiName,
                        flowTitle: eventDetail.flowTitle || this.flowTitle,
                        sessionId: this.sessionId,
                        status: eventDetail.status,
                        completedAt: new Date().toISOString(),
                        outputCount: Object.keys(outputObj).length
                    }
                };
                
                this.flowOutputsJson = JSON.stringify(enhancedOutput);
                
                console.log('Enhanced flow outputs captured:', this.flowOutputsJson);
                console.log('Output variables count:', Object.keys(outputObj).length);
                console.log('Storing with Session ID:', this.sessionId);
                
                // Automatically store outputs via Apex
                await this.storeOutputsInApex();
                
            } else {
                console.log('No output variables found in event detail');
                console.log('Available properties:', Object.keys(eventDetail));
                
                // Store empty result with metadata for tracking
                const emptyOutput = {
                    outputs: {},
                    metadata: {},
                    flowInfo: {
                        flowApiName: this.flowApiName,
                        flowTitle: eventDetail.flowTitle || this.flowTitle,
                        sessionId: this.sessionId,
                        status: eventDetail.status,
                        completedAt: new Date().toISOString(),
                        outputCount: 0,
                        note: 'Flow completed but no output variables were defined'
                    }
                };
                
                this.flowOutputsJson = JSON.stringify(emptyOutput);
                console.log('Storing empty result for tracking');
                
                // Still store empty result for tracking
                await this.storeOutputsInApex();
            }
        } catch (error) {
            console.error('Error capturing flow outputs:', error);
            console.error('Error stack:', error.stack);
            
            // Store error information
            const errorOutput = {
                outputs: {},
                metadata: {},
                flowInfo: {
                    flowApiName: this.flowApiName,
                    sessionId: this.sessionId,
                    status: 'ERROR',
                    error: error.message,
                    completedAt: new Date().toISOString()
                }
            };
            
            this.flowOutputsJson = JSON.stringify(errorOutput);
        }
    }

    // Store outputs using Apex method
    async storeOutputsInApex() {
        try {
            const request = {
                flowApiName: this.flowApiName,
                outputJson: this.flowOutputsJson,
                sessionId: this.sessionId
            };

            const result = await storeFlowOutputs({ requests: [request] });
            
            if (result && result.length > 0 && result[0].success) {
                console.log('Flow outputs stored successfully with key:', result[0].outputKey);
                
                // Dispatch event with storage confirmation for agent
                this.dispatchEvent(new CustomEvent('outputsstored', {
                    detail: {
                        success: true,
                        outputKey: result[0].outputKey,
                        sessionId: this.sessionId,
                        flowApiName: this.flowApiName,
                        outputsJson: this.flowOutputsJson
                    }
                }));
            } else {
                console.error('Failed to store flow outputs:', result);
                this.dispatchEvent(new CustomEvent('outputsstored', {
                    detail: {
                        success: false,
                        error: 'Storage failed',
                        sessionId: this.sessionId,
                        flowApiName: this.flowApiName
                    }
                }));
            }
        } catch (error) {
            console.error('Error storing flow outputs via Apex:', error);
            this.dispatchEvent(new CustomEvent('outputsstored', {
                detail: {
                    success: false,
                    error: error.message,
                    sessionId: this.sessionId,
                    flowApiName: this.flowApiName
                }
            }));
        }
    }

    // Getter for flow status CSS class
    get flowStatusClass() {
        let baseClass = 'flow-status';
        if (this.flowStatus === 'FINISHED') {
            return baseClass + ' status-finished';
        } else if (this.flowStatus === 'ERROR') {
            return baseClass + ' status-error';
        } else if (this.flowStatus === 'FINISHED_SCREEN') {
            return baseClass + ' status-finished-screen';
        }
        return baseClass;
    }

    // Public method for agent to get session info
    @api
    getSessionInfo() {
        return {
            sessionId: this.sessionId,
            flowApiName: this.flowApiName,
            flowStatus: this.flowStatus,
            hasOutputs: this.flowOutputsJson !== ''
        };
    }
}
